### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by radhakrishr36** [D2KLab/ZeSTE#1]
As per your documentation i run the generate_cache.py file but not generate the output files in the data/zeste/ folder. Help me to solve this issues or share the latest documentation.

**Comment by rtroncy** [comment]
Can you detail more the steps you performed and the error you have if any? Did you complete the Step 1 and downloaded the resources needed (ConceptNet triplets and embeddings)?

**Comment by radhakrishr36** [comment]
step1:

I downloaded  and unzip these two files.

step2: generate_cache.py 

While running this script first time my throw error(**killed**) . After change the read function now it's working. It's generate numberbatch-19.08.txt.pickle and 1.3k pickle file in data/zeste/ folder.

Step3: zeste.py

Now I am running the zeste.py file . I don't see the datasets/bbc_dataset.csv file in your git repositories , So I taken from the internet and run python script . Now it's throw the same error(**killed**) . 

The pickle file I am trying to load cannot be loaded on my computer. Even though I am running Linux server, I have 62GB of RAM.
numberbatch = pickle.load(open(args.numberbatch_path, 'rb'))

Please assist me in resolving this issue.

**Comment by Siliam** [comment]
Hello @radhakrishr36, can you please mention exactly what is the error you get? 
In the meantime I will try to upload the cached files into another hosting service because Github does not accept big files.

**Comment by radhakrishr36** [comment]
I solved the error in the code. but No files generated in neighborhoods and prefetch_neighborhoods directories after run the python scripts.
Does this code works correctly?

**Comment by Siliam** [comment]
Hello @radhakrishr36, I updated the code to correct some minor bugs. Could you please try the newer version and let me know if it works?

**Comment by creatorrr** [comment]
Hi @Siliam , the cache script works now but has some small bugs, for instance:
- the numberbatch file is output with the name `zeste_cache/numberbatch-en-19.08..pickle` instead of `zeste_cache/numberbatch-en-19.08.pickle` (not the extra dot in the former)
- the file nesting is somewhat buggy, nothing under `neighborhoods_en` folder

Fixing for these two in the `UI/server/zeste.py`, the cache now works as expected but I believe this should still be fixed in the caching script itself.

**Comment by ehrhart** [comment]
> the numberbatch file is output with the name zeste_cache/numberbatch-en-19.08..pickle instead of zeste_cache/numberbatch-en-19.08.pickle (not the extra dot in the former)

Nice catch! This has been fixed with 72dad70

> the file nesting is somewhat buggy, nothing under neighborhoods_en folder

Are you running `generate_cache.py` with the `-cnp` and `-nbp` arguments? For example, I'm using:

```bash
python3 generate_cache.py -cnp conceptnet-assertions-5.7.0.csv -nbp numberbatch-en-19.08.txt
```

**Comment by creatorrr** [comment]
Yup, I used:
`python3 generate_cache.py -cnp conceptnet-assertions-5.7.0.csv -nbp numberbatch-en-19.08.txt -zcp zeste_cache`

**Comment by ehrhart** [comment]
I've made several fixes to the codebase, @creatorrr could you please try:

1. Pulling the latest version (2a39179)
2. Generating the cache by using `python3 generate_cache.py -cnp conceptnet-assertions-5.7.0.csv -nbp numberbatch-en-19.08.txt -zcp zeste_cache`
3. Running ZeSTE on the default dataset by using `python3 zeste.py -cp zeste_cache -lm labels_mapping/bbc_labels_mapping.txt -dp data/bbc_dataset.csv -rp results`

**Comment by ehrhart** [comment]
I am closing this issue for now since it seems to be resolved, but if you are still having problems with it, please leave a comment, and I will re-open this.
